Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,4 +1,4 @@
-name: Attach files to release and upload to PPA
+name: Build packages for release
 
 on:
   release:
@@ -20,13 +20,11 @@ jobs:
     steps:
     - name: 🏷️ Check tag name
       run: |
-        echo "::group::Checking tag name"
         tag="${{ github.ref_name }}"
-        echo "$tag" | grep -Pq "^v\d+\.\d+\.\d+$" || (echo "Error: Tag name '$tag' does not correct." && exit 1)
-        echo "::endgroup::"
+        echo "$tag" | grep -Pq "^v\d+\.\d+\.\d+$" || (echo "::error::Tag name '$tag' does not correct." && exit 1)
 
     - name: 📥 Clone repository
-      uses: actions/checkout@v4.1.2
+      uses: actions/checkout@v4.1.5
 
     - name: ⚙️ Install dependencies
       # Temporary disable packages caching feature.
@@ -79,15 +77,14 @@ jobs:
         sudo usermod -aG lxd $USER
         sudo snap run lxd init --auto
         sudo snap run lxd waitready
+        echo "::endgroup::"
 
         # Login
         export SNAPCRAFT_STORE_CREDENTIALS="${{ secrets.SNAPCRAFT_CREDENTIALS }}"
 
         # Get version from tag
-        echo "::group::Get version from tag"
         tag="${{ github.ref_name }}"
         release_version=$(echo "$tag" | sed 's/v//g')
-        echo "::endgroup::"
 
         # Build snap package
         echo "::group::Building snap package"
